export const translations = {
  ar: {
    app_title: " خذلك بريك  ",
      login: "تسجيل الدخول",
  login_btn: "دخول",
  password: "كلمة المرور",
  add_item: "إضافة صنف",
  item_name: "اسم الصنف",
  price: "السعر",
  save_item: "حفظ الصنف",
  current_items: "الأصناف الحالية",
  back_to_cashier: "رجوع للكاشير",
    products: "الأصناف",
    reports_archive: "أرشيف التقارير",
date: "التاريخ",
orders_count: "عدد الطلبات",
total_sales: "إجمالي المبيعات",
actions: "الإجراءات",
view: "عرض",
no_reports: "لا توجد تقارير محفوظة",
back: "رجوع",
delete_report_error: "❌ فشل حذف التقرير",
    food: "طعام",
    drinks: "مشروبات",
    sides: "جانبية",
    invoice: "الفاتورة",
    item: "الصنف",
    qty: "الكمية",
    total: "المجموع",
    grand_total: "الإجمالي:",
    paid_amount: "المبلغ المدفوع",
    change: "الباقي:",
    complete_order: "إتمام الطلب",
    reports: "أرشيف التقارير",
    wrong_password: "كلمة المرور غير صحيحة",
    
enter_name_price: "أدخل الاسم والسعر",
save_item_error: "خطأ في حفظ الصنف",
load_items_error: "خطأ في تحميل الأصناف",
no_items: "لا توجد أصناف",
status: "الحالة",
active: "نشط",
disabled: "معطّل",
disable: "تعطيل",
enable: "تفعيل",
delete_final: "حذف نهائي",
update_status_error: "فشل تحديث الحالة",
confirm_delete_item: "⚠️ حذف نهائي! فقط إذا لم يُستخدم الصنف سابقًا.",
delete_item_used: "❌ لا يمكن حذف الصنف لأنه مستخدم في طلبات سابقة",
item_deleted: "🗑 تم حذف الصنف نهائيًا",
    close_day: "إقفال اليوم",
    manage_items: "إدارة الأصناف",
    daily_report: "تقرير إقفال اليوم",
orders_count: "عدد الطلبات",
total_sales: "إجمالي المبيعات",
top_item: "الأكثر مبيعًا",
items_details: "تفاصيل الأصناف",
new_day: "بدء يوم جديد",
download_pdf: "تحميل PDF",
report_footer: "تم إنشاء التقرير تلقائيًا بواسطة خذلك بريك 👨🏻‍🍳 ",
    
    active_orders: "الطلبات الجارية"
    
    


  },
  en: {
    app_title: "Cashier System",
    wrong_password: "Wrong password",
    reports_archive: "Reports Archive",
date: "Date",
orders_count: "Orders Count",
total_sales: "Total Sales",
 login: "Login",
  login_btn: "Enter",
  password: "Password",
  add_item: "Add Item",
  item_name: "Item Name",
  price: "Price",
  save_item: "Save Item",
  current_items: "Current Items",
  back_to_cashier: "Back to Cashier",
daily_report: "Daily Close Report",
orders_count: "Orders Count",
total_sales: "Total Sales",
top_item: "Top Item",
items_details: "Items Details",
new_day: "Start New Day",
download_pdf: "Download PDF",
report_footer: "Report generated automatically by the cashier system",
actions: "Actions",
view: "View",
no_reports: "No saved reports",
back: "Back",
delete_report_error: "❌ Failed to delete report",
enter_name_price: "Enter name and price",
save_item_error: "Failed to save item",
load_items_error: "Failed to load items",
no_items: "No items available",
status: "Status",
active: "Active",
disabled: "Disabled",
disable: "Disable",
enable: "Enable",
delete_final: "Delete permanently",
update_status_error: "Failed to update status",
confirm_delete_item: "⚠️ Permanent delete! Only if item was never used.",
delete_item_used: "❌ Cannot delete item because it was used before",
item_deleted: "🗑 Item deleted successfully",

    products: "Products",
    food: "Food",
    drinks: "Drinks",
    sides: "Sides",
    invoice: "Invoice",
    item: "Item",
    qty: "Qty",
    total: "Total",
    grand_total: "Total:",
    paid_amount: "Paid Amount",
    change: "Change:",
    complete_order: "Complete Order",
    reports: "Reports Archive",
    close_day: "Close Day",
    manage_items: "Manage Items",
    active_orders: "Active Orders"
  }
};

